PLAYERS_FILE_PATH = "Data/players.json"
TOURNAMENT_FILE_PATH = "Data/Tournaments/"

TITLE_STYLE = "bold blue"
LINE_STYLE = "blue"
ERROR_STYLE = "red"
SUCCESS_STYLE = "green"
TEXT_STYLE = "#77DFFE"
REQUEST_STYLE = "yellow"
INFORMATION_STYLE = "magenta"
